#!/bin/sh
DISTRO_NAME="$(cat /usr/lib/os-release | grep -i "PRETTY_NAME" | cut -d '=' -f 2 | sed 's/"//g')"
SCRIPT_DIR="$(readlink -f $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd ))"
SCRIPT_USER="$(whoami)"
BACKTITLE="[$SCRIPT_USER] $DISTRO_NAME settings > Time and date > Set date"
[ $SCRIPT_USER != "root" ] && echo "[ERROR] You must be root to run this script" && exit 1

CONTINUE=0; while [ $CONTINUE == 0 ]; do
	DATE=$(dialog --stdout --week-start locale --date-format %Y-%m-%d --backtitle "$BACKTITLE" --title "Set date" --calendar "Please select today's date" 0 0)
	[ -z "$DATE" ] && exit 1
	YEAR=$(echo "$DATE" | cut -d '-' -f 1); if [ $YEAR -lt 2024 ]; then
		dialog --backtitle "$BACKTITLE" --title "Warning" --yesno "You have set the date before 2024. Some programs may become unstable.\n\nReally set the date to $DATE?" 0 0 && CONTINUE=1
	else CONTINUE=1; fi
done

timedatectl set-time $DATE $(timedatectl | grep -i "Local time:" | cut -d '-' -f 3 | cut -d ' ' -f 2)
