#!/bin/sh
UidToUsername() {
	cat /etc/passwd | grep ":x:$1:" | cut -d ':' -f 1
}
DISTRO_NAME="$(cat /usr/lib/os-release | grep -i "PRETTY_NAME" | cut -d '=' -f 2 | sed 's/"//g')"
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

while true; do
	USERS=""
	UID_MIN=$(grep -E '^UID_MIN' /etc/login.defs | sed s/"UID_MIN"//)
	UID_MAX=$(grep -E '^UID_MAX' /etc/login.defs | sed s/"UID_MAX"//)
	if [ -z "$($SCRIPT_DIR/guest | grep "enabled")" ]; then GUEST_ENABLED=0; GUEST_ENABLE_TEXT="Enable"
	else GUEST_ENABLED=1; GUEST_ENABLE_TEXT="Disable"; fi
	while read -r LINE; do
		CURRENT_UID=$(echo "$LINE" | cut -d ':' -f 3)
		if [ $CURRENT_UID -ge $UID_MIN ] && [ $CURRENT_UID -le $UID_MAX ]; then
			USERS="$USERS $CURRENT_UID $(echo "$LINE" | cut -d ':' -f 1)"
		fi
	done < /etc/passwd
	CHOICE=$(dialog --stdout --backtitle "$DISTRO_NAME settings" --title "Users" --menu "Manage users" 0 0 0 $USERS "a" "Add user" "g" "$GUEST_ENABLE_TEXT guest account")
	if [ -z "$CHOICE" ]; then exit 125
	elif [ "$CHOICE" == "a" ]; then sudo "$SCRIPT_DIR/adduser"
	elif [ "$CHOICE" == "g" ]; then
		[ $GUEST_ENABLED == 1 ] && sudo "$SCRIPT_DIR/guest" enable || sudo "$SCRIPT_DIR/guest" disable
	else
		USERNAME=$(UidToUsername $CHOICE)
	fi
done
