#!/bin/sh
DISTRO_NAME="$(cat /usr/lib/os-release | grep -i "PRETTY_NAME" | cut -d '=' -f 2 | sed 's/"//g')"
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
USERNAME="$1"
[ -z "$USERNAME" ] && echo "[ERROR] No user specified" && exit 1
while true; do
	CHOICE=$(dialog --stdout --backtitle "$DISTRO_NAME settings" --title "Users" --menu "Settings for $USERNAME" 0 0 0 "p" "Password" "a" "Administrator" "e" "Encrypt home directory" "d" "Delete user")
	if [ -z "$CHOICE" ]; then exit 125
	fi
done
