#!/bin/sh
[ "$(whoami)" != "root" ] && echo "[ERROR] You must run this script as root" && exit 13
DISTRO_NAME="$(cat /usr/lib/os-release | grep -i "PRETTY_NAME" | cut -d '=' -f 2 | sed 's/"//g')"
REGDOMS="00 GB IE AU NZ US CA AL DZ AS AD AI AR AM AW AT AZ BS BH BD BB BY BE BZ BM BT BO BA BR BN BG BF KH KY CF TD CL CN CX CO CR CI HR CU CY CZ DK DM DO EC EG SV EE ET FI FR GF PF GE DE GH GR GL GD GP GU GY GT HT HN HK HU IS IN ID IR IL IT JM JP JO KZ KE KP KR KW LV LB LS LI LT LU MO MW MY MV MT MH MQ MR MU YT MX FM MD MC MN ME MA NP NL AN NI NG MP NP MK NO OM PK PW PA PG PY PE PH PL PT PR QA RE RO RU RW BL KN LC MF PM VC WS SA SN RS SG SK SI ZA ES LK SR SE CH SY TW TZ TH TG TT TN TR TC UG UA AE UY UZ VU VE VN VI WF YE ZW"
CodeToCountry() {
	case $1 in
		AD) echo "Andorra";;
		AE) echo "United Arab Emirates";;
		AF) echo "Afghanistan";;
		AI) echo "Anguilla";;
		AL) echo "Albania";;
		AM) echo "Armenia";;
		AN) echo "Netherlands Antilles";;
		AR) echo "Argentina";;
		AS) echo "American Samoa";;
		AT) echo "Austria";;
		AU) echo "Australia";;
		AW) echo "Aruba";;
		AZ) echo "Azerbaijan";;
		BA) echo "Bosnia and Herzegovina";;
		BB) echo "Barbados";;
		BD) echo "Bangladesh";;
		BE) echo "Belgium";;
		BF) echo "Burkina Faso";;
		BG) echo "Bulgaria";;
		BH) echo "Bahrain";;
		BL) echo "Saint Barthélemy";;
		BM) echo "Bermuda";;
		BN) echo "Brunei Darussalam";;
		BO) echo "Bolivia";;
		BR) echo "Brazil";;
		BS) echo "Bahamas";;
		BT) echo "Bhutan";;
		BY) echo "Belarus";;
		BZ) echo "Belize";;
		CA) echo "Canada";;
		CF) echo "Central African Republic";;
		CH) echo "Switzerland";;
		CI) echo "Côte d'Ivoire";;
		CL) echo "Chile";;
		CN) echo "China";;
		CO) echo "Columbia";;
		CR) echo "Costa Rica";;
		CU) echo "Cuba";;
		CX) echo "Christmas Island";;
		CY) echo "Cyprus";;
		CZ) echo "Czechia";;
		DE) echo "Germany";;
		DK) echo "Denmark";;
		DM) echo "Dominica";;
		DO) echo "Dominican Republic";;
		DZ) echo "Algeria";;
		EC) echo "Ecuador";;
		EE) echo "Estonia";;
		EG) echo "Egypt";;
		ES) echo "Spain";;
		ET) echo "Ethiopia";;
		FI) echo "Finland";;
		FM) echo "Micronesia";;
		FR) echo "France";;
		GB) echo "United Kingdom of Great Britain and Northern Ireland";;
		GD) echo "Grenada";;
		GE) echo "Georgia";;
		GF) echo "French Guiana";;
		GH) echo "Ghana";;
		GL) echo "Greenland";;
		GP) echo "Guadeloupe";;
		GR) echo "Greece";;
		GT) echo "Guatemala";;
		GU) echo "Guam";;
		GY) echo "Guyana";;
		HK) echo "Hong Kong";;
		HN) echo "Honduras";;
		HR) echo "Croatia";;
		HT) echo "Haiti";;
		HU) echo "Hungary";;
		ID) echo "Indonesia";;
		IE) echo "Ireland, Republic of";;
		IL) echo "Israel";;
		IN) echo "India";;
		IR) echo "Iran";;
		IS) echo "Iceland";;
		IT) echo "Italy";;
		JM) echo "Jamaica";;
		JO) echo "Jordan";;
		JP) echo "Japan";;
		KE) echo "Kenya";;
		KH) echo "Cambodia";;
		KN) echo "Saint Kitts and Nevis";;
		KP) echo "Korea, Democratic People's Republic of";;
		KR) echo "Korea, Republic of";;
		KW) echo "Kuwait";;
		KY) echo "Cayman Islands";;
		KZ) echo "Kazakhstan";;
		LB) echo "Lebanon";;
		LC) echo "Saint Lucia";;
		LI) echo "Liechtenstein";;
		LK) echo "Sri Lanka";;
		LS) echo "Lesotho";;
		LT) echo "Lithuania";;
		LU) echo "Luxembourg";;
		LV) echo "Latvia";;
		MA) echo "Morocco";;
		MC) echo "Monaco";;
		MD) echo "Moldova";;
		ME) echo "Montenegro";;
		MF) echo "Saint Martin, French part";;
		MH) echo "Marshall Islands";;
		MK) echo "North Macedonia";;
		MN) echo "Mongolia";;
		MO) echo "Macao";;
		MP) echo "Northern Mariana Islands";;
		MQ) echo "Martinique";;
		MR) echo "Mauritania";;
		MT) echo "Malta";;
		MU) echo "Mauritius";;
		MV) echo "Maldives";;
		MW) echo "Malawi";;
		MX) echo "Mexico";;
		MY) echo "Malaysia";;
		NG) echo "Nigeria";;
		NI) echo "Nicaragua";;
		NL) echo "Netherlands";;
		NO) echo "Norway";;
		NP) echo "Nepal";;
		NZ) echo "New Zealand";;
		OM) echo "Oman";;
		PA) echo "Panama";;
		PE) echo "Peru";;
		PF) echo "French Polynesia";;
		PG) echo "Papua New Guinea";;
		PH) echo "Philippines";;
		PK) echo "Pakistan";;
		PL) echo "Poland";;
		PM) echo "Saint Pierre and Miquelon";;
		PR) echo "Puerto Rico";;
		PT) echo "Portugal";;
		PW) echo "Palau";;
		PY) echo "Paraguay";;
		QA) echo "Qatar";;
		RE) echo "Réunion";;
		RO) echo "Romania";;
		RS) echo "Serbia";;
		RU) echo "Russia";;
		RW) echo "Rwanda";;
		SA) echo "Saudi Arabia";;
		SE) echo "Sweden";;
		SG) echo "Singapore";;
		SI) echo "Slovenia";;
		SK) echo "Slovakia";;
		SN) echo "Senegal";;
		SR) echo "Suriname";;
		SV) echo "El Salvador";;
		SY) echo "Syrian Arab Republic";;
		TC) echo "Turks and Caicos Islands";;
		TD) echo "Chad";;
		TG) echo "Togo";;
		TH) echo "Thailand";;
		TN) echo "Tunisia";;
		TR) echo "Turkey";;
		TT) echo "Trinidad and Tobago";;
		TW) echo "Taiwan";;
		TZ) echo "Tanzania";;
		UA) echo "Ukraine";;
		UG) echo "Uganda";;
		US) echo "United States of America";;
		UY) echo "Uruguay";;
		UZ) echo "Uzbekistan";;
		VC) echo "Saint Vincent and the Grenadines";;
		VE) echo "Venezuela";;
		VI) echo "Virgin Islands (U.S.)";;
		VN) echo "Viet Nam";;
		VU) echo "Vanuatu";;
		WF) echo "Wallis and Futuna";;
		WS) echo "Samoa";;
		YE) echo "Yemen";;
		YT) echo "Mayotte";;
		ZA) echo "South Africa";;
		ZW) echo "Zimbabwe";;
		00) echo "World";;
		*) echo "Unknown/world";;
	esac
}

unset WIRELESS_REGDOM SELECTED_REGDOM
iw reg reload
if [ -z "$1" ]; then ## Prompt to select Wifi country
	# Get current regdomain
	[ -f /etc/conf.d/wireless-regdom ] && . /etc/conf.d/wireless-regdom
	[ -z $WIRELESS_REGDOM ] && WIRELESS_REGDOM="00"

	# Construct a dialog command to be inserted into a script, and append regdom choices to it
	DIALOG_CMD="echo \$(dialog --stdout --backtitle \"$DISTRO_NAME settings\" --title \"Wireless region\" --menu \"Please select wireless region (current: $(CodeToCountry $WIRELESS_REGDOM))\nIf your region isn't listed here, please select \\\"World\\\".\nIt is important to select the correct region to ensure wireless hardware complies with local laws set by Ofcom, FCC and other organizations.\nSetting an incorrect wireless region can cause radio interference and break local laws, and you could face prosecution.\" 0 0 0"
	for REGDOM in $REGDOMS; do
		DIALOG_CMD="$DIALOG_CMD \"$REGDOM\" \"$(CodeToCountry $REGDOM)\""
	done
	DIALOG_CMD="${DIALOG_CMD}) > /run/voscfg/syscfg-wirelessregion-answer"
	mkdir -p /run/voscfg
	echo "#!/bin/sh" > /run/voscfg/syscfg-wirelessregion
	echo "$DIALOG_CMD" >> /run/voscfg/syscfg-wirelessregion
	chmod +x /run/voscfg/syscfg-wirelessregion
	/run/voscfg/syscfg-wirelessregion
	SELECTED_REGDOM="$(cat /run/voscfg/syscfg-wirelessregion-answer)"
	rm /run/voscfg/syscfg-wirelessregion /run/voscfg/syscfg-wirelessregion-answer
else ## Use command line parameter instead
	if [[ "$REGDOMS" != *"$1"* ]]; then
		echo "[ERROR] Region code \"$1\" is not in wireless-regdb."
		echo "The available region codes are listed below:"
		for REGDOM in $REGDOMS; do
			echo "$REGDOM ($(CodeToCountry $REGDOM))"
		done
		echo "If your region isn't listed here, you should use code \"00\" (World)."
		echo "Wireless region has not been changed."
		exit 1
	else SELECTED_REGDOM="$1"; fi
fi

if [ ! -z "$SELECTED_REGDOM" ]; then ## Set the wireless country if one has been selected
	sed -i 's/^\([^#].*\)/#\1/g' /etc/conf.d/wireless-regdom # Comment all lines in /etc/conf.d/wireless-regdom
	sed -i "/^#WIRELESS_REGDOM=\"$SELECTED_REGDOM\"/ cWIRELESS_REGDOM=\"$SELECTED_REGDOM\"" /etc/conf.d/wireless-regdom # Uncomment regdomain
	echo "options cfg80211 ieee80211_regdom=$SELECTED_REGDOM" > /etc/modprobe.d/cfg80211-wireless-regdom.conf
	iw reg set $SELECTED_REGDOM # Set the regdomain now
	echo "Set wireless region to \"$SELECTED_REGDOM\" ($(CodeToCountry $SELECTED_REGDOM))"
else echo "Wireless region has not been changed."; exit 125; fi
