#!/bin/bash
#[ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "____   ____                                   ________    _________
\\   \\ /   /____  ______   ____  __ _________  \\_____  \\  /   _____/
 \\   Y   /\\__  \\ \\____ \\ /  _ \\|  |  \\_  __ \\  /   |   \\ \\_____  \\
  \\     /  / __ \\|  |_> >  <_> )  |  /|  | \\/ /    |    \\/        \\
   \\___/  (____  /   __/ \\____/|____/ |__|    \\_______  /_______  /
               \\/|__|                                 \\/        \\/"
exit
