# LiveUSB installer options.

# Specify partitions for installation. You can also specify partition labels, and whether to format them or not.
# All Arch Linux system files from the previous installation will be deleted regardless.
# You MUST specify a root partition and ESP.
LABEL_ROOT="VOSTEST"
DEV_ROOT="/dev/disk/by-label/$LABEL_ROOT"
FORMAT_ROOT=1
LABEL_BOOT="BOOTTEST"
DEV_BOOT="/dev/disk/by-label/$LABEL_BOOT"
FORMAT_BOOT=1
#LABEL_MEDIA="media"
DEV_MEDIA="/dev/disk/by-label/$LABEL_MEDIA"
FORMAT_MEDIA=0
#LABEL_HOME="home"
DEV_HOME="/dev/disk/by-label/$LABEL_HOME"
FORMAT_HOME=0
#LABEL_PUBLIC="public"
DEV_PUBLIC="/dev/disk/by-label/$LABEL_PUBLIC"
FORMAT_PUBLIC=0

#### [Basic system settings] ####
# First user account created - the device's "owner". Admin priviliges.
OWNER="alex4nder"
#
# Add other users to the system. No admin priviliges. They still have some permissions, including but not limited to:
# Wifi/bluetooth/GPS/modem - connect and toggle power, mount removable devices, realtime audio
#ADDUSERS=""
#
# Enable guest user. Exactly the same as a standard user, with the same permissions, except with a tmpfs home directory (max 25% of RAM).
# At least 1.5GiB RAM recommended.
#ENABLEGUEST=1
#
# Hostname
HOST_NAME="alex4nder-laptop"
#
# Default locale to be used. This, en_US and C will be generated and used as fallback locales in this order.
LOCALE="en_GB.UTF-8"
#
# Console and X11 keyboard layout
KEYMAP="uk"
#
# Time zone
TIMEZONE="Europe/London"
#
# Display size in inches diagonal
DISPLAY_SIZE=17.3
#
# Wireless regulatory domain
REGDOMAIN="GB"

# List of extra packages to be installed afterwards. Depending on your use case, you will probably want to install some of the Vapour OS meta-packages that make installing extra features easily. Choose a desktop environment, or just a simple GUI, multimedia codecs, game software and libraries, print/filesharing services etc. AUR software is also supported thanks to Yay.
EXTRA_SOFTWARE="firefox-i18n-en-gb gparted libreoffice-fresh-en-gb qbittorrent seahorse vlc"
EXTRA_SOFTWARE="$EXTRA_SOFTWARE audacity discord lmms mkvtoolnix-gui obs-studio vdhcoapp-bin yuzu-mainline-bin"
EXTRA_SOFTWARE="$EXTRA_SOFTWARE eduke32 gzdoom minecraft-launcher nblood-git nvidia-prime steam-native-runtime"
EXTRA_SOFTWARE="$EXTRA_SOFTWARE libretro-desmume libretro-fbneo libretro-genesis-plus-gx libretro-mesen libretro-nestopia libretro-parallel-n64 libretro-sameboy libretro-snes9x libretro-vba-next-git retroarch-assets-ozone"
EXTRA_SOFTWARE="$EXTRA_SOFTWARE dolphin-emu dosbox-x-sdl2 duckstation-git openglide-git pcsx2 rpcs3-bin vice-sdl2"
