# Specify partitions for installation. You can also specify partition labels, and whether to format them or not.
# All Arch Linux system files from the previous installation will be deleted regardless.
# You MUST specify a root partition and ESP.
LABEL_ROOT="VOSTEST"; DEV_ROOT="/dev/disk/by-label/$LABEL_ROOT"; FORMAT_ROOT=0
LABEL_BOOT="BOOTTEST"; DEV_BOOT="/dev/disk/by-label/$LABEL_BOOT"; FORMAT_BOOT=0
#LABEL_MEDIA="media"; DEV_MEDIA="/dev/disk/by-label/$LABEL_MEDIA"; FORMAT_MEDIA=0
#LABEL_HOME="home"; DEV_HOME="/dev/disk/by-label/$LABEL_HOME"; FORMAT_HOME=0
#LABEL_PUBLIC="public"; DEV_PUBLIC="/dev/disk/by-label/$LABEL_PUBLIC"; FORMAT_PUBLIC=0

DISPLAY_WIDTH=383				# Display width (horizontal) in mm. Must be an non-zero positive integer.
DISPLAY_HEIGHT=215				# Display height (vertical) in mm. Must be an non-zero positive integer.
DISPLAY_XRES=1920				# Display width (horizontal) in pixels. Must be an non-zero positive integer.
DISPLAY_YRES=1080				# Display height (vertical) in pixels. Must be an non-zero positive integer.
DISPLAY_NAME="eDP1"				# Name of the primary display in Xorg. Make sure this is correct or Xorg will fail to start. If unsure, leave blank.
OWNER="alex4nder"				# The first user account created. This is the "owner" of the device, and will be given admin priviliges.
PKG_EXTRA="firefox"				# Extra packages to be installed afterwards
LOCALE="en_GB.UTF-8"			# Locale to use
HOST_NAME="alex4nder-laptop"	# Machine host name - will be saved to /etc/hostname
KEYMAP="uk"						# Console keymap - will be saved to /etc/vconsole.conf
XKEYMAP="gb"					# X11 keymap - will be saved to /etc/X11/xorg.conf.d/00-keyboard.conf
TIMEZONE="Europe/London"		# Time zone - will be saved to /etc/localtime
REGDOMAIN="GB"					# Wireless regulatory domain