LABEL_ROOT="VOSTEST"
ROOT_DEV="/dev/disk/by-label/$LABEL_ROOT"
FORMAT_ROOT=1

LABEL_BOOT="BOOTTEST"
BOOT_DEV="/dev/disk/by-label/$LABEL_BOOT"
FORMAT_BOOT=1

LABEL_MEDIA="media"
MEDIA_DEV="/dev/disk/by-label/$LABEL_MEDIA"
FORMAT_MEDIA=0

# LABEL_HOME="home"
# HOME_DEV="/dev/disk/by-label/$LABEL_HOME"
# FORMAT_HOME=0
# LABEL_PUBLIC="public"
# PUBLIC_DEV="/dev/disk/by-label/$LABEL_PUBLIC"
# FORMAT_PUBLIC=0

OWNER="alex4nder" # Required
GUEST=1 # Add a guest user with a home directory in tmpfs. Will be lost upon reboot/shutdown.
HOST_NAME="alex4nder-laptop"
LOCALE="en_GB.UTF-8"
KEYMAP="uk"
TIMEZONE="Europe/London"
DISPLAY_SIZE=17.3 # Diagonal display size in inches
REGDOMAIN="GB" # Wireless regulatory domain

# # Whether or not to install vapour-os-gui, the X11 and Pipewire base libraries. 0=None; 1=vapour-os-gui; 2=;lib32-vapour-os-gui
# IMPORTANT! You MUST install vapour-os-gui BEFORE installing any graphical/multimedia packages or desktops, and lib32-vapour-os-gui
# BEFORE installing any 32 bit graphical/multimedia packages (especially gaming). This is due to dependency conflicts between pipewire-jack and jack2, for example.
GRAPHICAL=2

# List of extra packages to be installed afterwards (supports AUR as well).
EXTRA_SOFTWARE="firefox-i18n-en-gb gparted libreoffice-fresh-en-gb qbittorrent seahorse vlc"
#EXTRA_SOFTWARE="$EXTRA_SOFTWARE audacity discord lmms mkvtoolnix-gui obs-studio vdhcoapp-bin yuzu-mainline-bin"
#EXTRA_SOFTWARE="$EXTRA_SOFTWARE eduke32 gzdoom minecraft-launcher nblood-git nvidia-prime steam-native-runtime"
#EXTRA_SOFTWARE="$EXTRA_SOFTWARE libretro-desmume libretro-fbneo libretro-genesis-plus-gx libretro-mesen libretro-nestopia libretro-parallel-n64 libretro-sameboy libretro-snes9x libretro-vba-next-git retroarch-assets-ozone"
#EXTRA_SOFTWARE="$EXTRA_SOFTWARE dolphin-emu dosbox-x-sdl2 duckstation-git openglide-git pcsx2 rpcs3-bin vice-sdl2"
