#!/bin/sh
[ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
$SCRIPT_DIR/diskinfo

echo "## Root partition" > /etc/fstab
echo "UUID=$ROOT_UUID / ext4 rw,lazytime 0 1" >> /etc/fstab
echo "" >> /etc/fstab
echo "## EFI system partition" >> /etc/fstab
echo "UUID=$BOOT_UUID /boot vfat rw,noatime,noexec,noauto,x-systemd.automount,dmask=0022,fmask=133,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro 0 2" >> /etc/fstab
echo "" >> /etc/fstab
[ ! -z "$HOME_DEV" ] && echo "## Home partition" >> /etc/fstab && \
	echo "UUID=$HOME_UUID /home ext4 rw,lazytime,noauto,x-systemd.automount 0 2" >> /mnt/etc/fstab && \
	echo "" >> /etc/fstab
[ ! -z "$MEDIA_DEV" ] && echo "## Media partition" >> /etc/fstab && \
	echo "UUID=$MEDIA_UUID /media ext4 rw,noatime,noauto,x-systemd.automount 0 2" >> /etc/fstab && \
	echo "" >> /etc/fstab
[ ! -z "$PUBLIC_DEV" ] && echo "## Public partition" && \
	"UUID=$PUBLIC_UUID /public ext4 rw,noatime,noauto,x-systemd.automount 0 2" >> /etc/fstab && \
	echo "" >> /etc/fstab
systemctl daemon-reload
