#!/bin/sh
[ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
GUEST=$1
[ -z $GUEST ] && echo "[WARNING] Leaving guest unchanged" && exit 0

RemoveGuest() {
	pkill -9 -u guest &> /dev/null
	userdel -f guest &> /dev/null
	umount -f /home/guest &> /dev/null
	rm -rf /home/guest
	$SCRIPT_DIR/fstab
}

AddGuest() {
	mkdir /home/guest
	$SCRIPT_DIR/fstab
	mount /home/guest
	useradd guest
	chmod 700 /home/guest
	chown -R guest:guest /home/guest
	passwd -d guest &> /dev/null
}

if [ $GUEST == 1 ]; then AddGuest
elif [ $GUEST == 0 ]; then RemoveGuest
else echo "[ERROR] Invalid value! (must be 1 or 0)"; exit 1; fi
