#!/bin/sh
[ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
$SCRIPT_DIR/setvar set /etc/lsb-release DISTRIB_ID "\"vapour-os\""
$SCRIPT_DIR/setvar set /etc/lsb-release DISTRIB_DESCRIPTION "\"Vapour OS\""
