#!/bin/sh
[ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
$SCRIPT_DIR/setvar set /usr/lib/os-release NAME "\"Vapour OS\""
$SCRIPT_DIR/setvar set /usr/lib/os-release PRETTY_NAME "\"Vapour OS\""
$SCRIPT_DIR/setvar set /usr/lib/os-release ID "vapour-os"
$SCRIPT_DIR/setvar set /usr/lib/os-release ID_LIKE "arch"
$SCRIPT_DIR/setvar set /usr/lib/os-release DEFAULT_HOSTNAME "vapour-os"
