#!/bin/sh
[ "$(whoami)" != "root" ] && echo "[ERROR] You must run this script as root" && exit 13
DISTRO_NAME="$(cat /usr/lib/os-release | grep -i "PRETTY_NAME" | cut -d '=' -f 2 | sed 's/"//g')"
SCRIPT_USER=$(whoami)
BACKTITLE="$DISTRO_NAME settings [$SCRIPT_USER]"

unset INPUT
if [ -z "$1" ]; then ## Prompt to enter static hostname
	INPUT="$(dialog --stdout --backtitle "$BACKTITLE" --title "System hostname" --inputbox "Enter a static hostname, used to identify this device on a network. It must:\n - Include only letters, numbers and hyphens (-)\n - Not start with a hyphen\n - Not exceed 64 characters" 0 0)"
else INPUT="$1"; fi ## Use command line parameter instead

if [ ! -z "$INPUT" ]; then
	## Check validity of hostname
	if ! [[ "$INPUT" =~ ^[0-9A-Za-z-]+$ ]]; then echo "[ERROR] Hostname contains illegal characters. Not changing hostname."; exit 1 # Check for illegal characters
	elif (($(expr length "$INPUT") > 64)); then echo "[ERROR] Hostname is longer than 64 characters. Not changing hostname."; exit 1 # Check if hostname is too long
	elif [ ${INPUT:0:1} == "-" ]; then echo "[ERROR] Hostname must not begin with a hyphen (-). Not changing hostname."; exit 1 # Check if hostname starts with hyphen
	elif [ ${INPUT:0:1} == "_" ]; then echo "[ERROR] Hostname must not begin with an underscore (_). Not changing hostname."; exit 1 # Check if hostname starts with underscore
	fi

	## Set the hostname
	touch /etc/hostname /etc/hosts
	unset OLD_HOSTNAME; OLD_HOSTNAME="$(cat /etc/hostname)"
	hostnamectl --static hostname "$INPUT" || echo "$INPUT" > /etc/hostname

	## Set hostname in /etc/hosts
	EMPTY=1; while read -r LINE; do # Check if /etc/hosts is empty (no non-comment lines)
		[ "${LINE:0:1}" != "#" ] && EMPTY=0;
	done < /etc/hosts
	if [ $EMPTY == 1 ] || [ -z "$OLD_HOSTNAME" ]; then # If file is empty, or hostname is unset, write the file
		echo "127.0.0.1 localhost" > /etc/hosts
		echo "::1 localhost" >> /etc/hosts
		echo "127.0.1.1 $INPUT" >> /etc/hosts
	else sed -i "s/$OLD_HOSTNAME/$INPUT/g" /etc/hosts; fi # Otherwise replace old hostname with new hostname
else echo "Static hostname has not been changed"; exit 125; fi
