#!/bin/sh
KERNELS=""; for KMOD_DIR in $(ls -v -w 1 /usr/lib/modules); do
KERNELS="$KERNELS $(cat /usr/lib/modules/$KMOD_DIR/pkgbase)"; done

for KMOD_DIR in $(ls -v -w 1 /usr/lib/modules); do
	CURRENT_KERNEL_NAME=$(cat /usr/lib/modules/$KMOD_DIR/pkgbase)
	## If that kernel is no longer installed, remove modules
	if [[ " $KERNELS " != *" $CURRENT_KERNEL_NAME "* ]]; then
		rm -rf /usr/lib/modules/$KMOD_DIR
	else
		if [ "$(vercmp $(uname -r) $KMOD_DIR)" == "1" ]; then
			rm -rf /usr/lib/modules/$KMOD_DIR
		fi
	fi
done
