## WARNING: Any changes to this file will be lost after vapour-os-gaming
## is upgraded. If you wish to change these defaults, create a file with
## a numerically/alphabetically higher filename and it will be read after
## this file.

GAMEDIR=/public/games
WINEESYNC=1 
DXVK_CONFIG_FILE=/etc/dxvk.conf
DXVK_LOG_PATH=none
DXVK_LOG_LEVEL=none
VKD3D_CONFIG=force_host_cached,force_static_cbv
VKD3D_DEBUG=none
VKD3D_SHADER_DEBUG=none
VKD3D_TEST_DEBUG=0
