#!/bin/sh
DISTRO_ID="vapour-os"
DISTRO_NAME="Vapour OS"
if [ -f /usr/bin/nano ] && [ ! -f /etc/nanorc.pacnew ]; then
	cp /usr/share/$DISTRO_ID/custom-configs/nanorc /etc/nanorc &> /dev/null
	cp -n /usr/share/$DISTRO_ID/custom-configs/root.nanorc /root/.nanorc &> /dev/null
fi
exit 0
