#!/bin/sh
DISTRO_ID="vapour-os"

# Install .pacnew config files
# We want to make sure the mirrorlists are up to date first,
# as they won't be upgraded automatically after being renamed.
/usr/share/libalpm/scripts/$DISTRO_ID/mirrors
for FILE in $(find /etc -name "*.pacnew"); do
	mv $FILE $(echo "$FILE" | rev | cut -c8- | rev)
done
