# This file is included with the Vapour OS AMD GPU package.
# You may edit this file, and all changes will be kept after an update.
Section "Device"
	Identifier "AMD"
	Driver "amdgpu"
	Option "TearFree" "false"
	Option "VariableRefresh" "true"
EndSection
