# Specify partitions for installation. You can also specify whether to format them or not.
# All Arch Linux system files from the previous installation will be deleted regardless.
# You MUST specify a root partition and ESP.
DEV_ROOT="/dev/disk/by-label/arch";			FORMAT_ROOT=0
DEV_BOOT="/dev/disk/by-label/BOOT";			FORMAT_BOOT=0
#DEV_MEDIA="/dev/disk/by-label/media";		FORMAT_MEDIA=0
#DEV_HOME="/dev/disk/by-label/home";		FORMAT_HOME=0
#DEV_PUBLIC="/dev/disk/by-label/public";	FORMAT_PUBLIC=0

DISPLAY_SCALE=100				# Display scale in percent. Must be an integer between 25 and 1000. If text appears too small increase this value.
OWNER="alex4nder"				# The first user account created. This is the "owner" of the device, and will be given admin priviliges.
PKG_EXTRA=""					# Extra packages to be installed afterwards
LOCALE="en_GB.UTF-8"			# Locale to use
HOST_NAME="alex4nder-server"	# Machine host name - will be saved to /etc/hostname
KEYMAP="uk"						# Console keymap - will be saved to /etc/vconsole.conf
XKEYMAP="gb"					# X11 keymap - will be saved to /etc/X11/xorg.conf.d/00-keyboard.conf
TIMEZONE="Europe/London"		# Time zone - will be saved to /etc/localtime