## WARNING: Any changes to this file will be lost after vapour-os-gui is
## upgraded. If you wish to change these defaults, create a file with a
## numerically/alphabetically higher filename and it will be read after
## this file.

GTK_USE_PORTAL=1
_JAVA_OPTIONS=-Dswing.aatext=TRUE -Dawt.useSystemAAFontSettings=on -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
