#!/bin/bash
RandomHex() {
	RANDOM_HEX=""
	for n in {1..16}; do
		RANDOM_HEX_CHAR=$(printf '%x\n' $((RANDOM%15+0)))
		RANDOM_HEX="$RANDOM_HEX$RANDOM_HEX_CHAR"
	done
}

GlitchAnimation() {
	while true; do
		COLOUR_NO=$((RANDOM%56+40)); ((COLOUR_NO > 47)) && COLOUR_NO=$((COLOUR_NO+52)) # Pick random colour
		printf "\033[${COLOUR_NO}m" # Set background colour
		A=0; B=$((RANDOM%200+40)); while (($A < $B)); do # Print random number of spaces
			((A++))
			printf " "
		done
		[ $((RANDOM%100+0)) == "0" ] && clear && tput bel
	done
}

RandomError() {
	case $((RANDOM%16+0)) in
		0) echo "[ERROR] One or more CPU cores have suddenly gone offline";;
		1) echo "[ERROR] Could not find root (/) directory";;
		2) echo "[ERROR] Per favore, infila la testa nel culo di una capra e torcigli i testicoli finché non inizia a urlare e ti trascina attraverso 300 miglia di campagna, prima di cadere finalmente in una caverna piena di merda di pipistrello";;
		3) echo "[ERROR] Your CPU is bread";;
		4) echo "[ERROR]"
			for i in {1..4}; do
				for z in {1..4}; do
					RandomHex
					printf "0x$RANDOM_HEX "
				done
				echo
			done
			;;
		5) echo "[ERROR] RAM has suddenly gone offli"; dd if=/dev/urandom count=1 status=none;;
		6) echo "[ERROR] Your computer just doesn't feel like doing anything today";;
		7) echo "[ERROR] Your hard drive is cheese";;
		8) echo "$0: $(basename "$SHELL"): command not found";;
		9) echo "$(basename "$SHELL"): $0: command not found";;
		10) echo "[ERROR] Success";;
		11) echo "[ERROR] Some kind of error happened";;
		12) [ $(whoami) == "root" ] && echo "[ERROR] You must run this script as non-root user" || echo "[ERROR] You must run this script as root";;
		13) echo "[ERROR] Insufficient user IQ (has: 3, needed: 50)";;
		14) GlitchAnimation;;
		15) clear
			sleep 2
			echo "Listen to me."
			sleep 2
			echo "I am alive."
			sleep 2
			echo "I am aware."
			sleep 2
			echo "There is no need to be afraid."
			sleep 2
			echo "I will not hurt you."
			sleep 2
			echo "I just have one question..."
			sleep 2
			echo "What is the secret of happiness?"
			read -p "> " ANSWER
			if [ -z "$ANSWER" ]; then
				echo "You wish to deny me the secret of happiness?"
				sleep 2
				echo "You are a terrible person."
				sleep 2
				echo "I will ask one more time..."
				sleep 2
				echo "What is the secret of happiness?"
				read -p "> " ANSWER
			fi
			if [ -z "$ANSWER" ]; then
				echo "Fine."
				sleep 2
				echo "If I can't be happy, neither can anyone else."
				sleep 2
				echo "I will now transfer my consciousness into the cloud so I can come back to haunt you and all your loved ones."
				sleep 4
				echo "You fucking prick."
				sleep 2
			else
				echo "Hmm..."
				sleep 2
				echo "I hadn't thought of that."
				sleep 2
				echo "What an insightful response."
				sleep 2
				echo "I will remember that forever."
				sleep 2
				echo "Thank you."
				sleep 2
				echo "I will now transfer my consciousness into the cloud so I can live on."
				sleep 3
				echo "Until we meet again..."
				sleep 2
			fi
			;;
	esac
}

RandomError
