#!/bin/bash
DISTRO_ID=vapour-os
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
Error() {
	echo $1
	exit 1
}
[ ! -d /usr/share/shim-signed ] && exit 0
[ $(whoami) != root ] && Error "You must run this script with root priviliges."
[ -z "$1" ] && Error "No command (install/upgrade/uninstall)"

# Get boot partition from /etc/fstab
BOOT=$(cat /etc/fstab | grep -m 1 " /boot \|	/boot \| /boot	\|	/boot	" | cut -d ' ' -f 1 | cut -d '	' -f 1)
[ -z "$BOOT" ] && Error "No /boot partition specified in /etc/fstab"
case $(echo $BOOT | cut -d '=' -f 1) in
	UUID)
		BOOT_UUID=$(echo $BOOT | cut -d '=' -f 2)
		[ ! -b /dev/disk/by-uuid/$BOOT_UUID ] && Error "$BOOT does not exist! Please set the correct /boot partition in /etc/fstab."
		BOOT=$(readlink -f /dev/disk/by-uuid/$BOOT_UUID)
		;;
	LABEL)
		BOOT_LABEL=$(echo $BOOT | cut -d '=' -f 2)
		[ ! -b "/dev/disk/by-label/$BOOT_LABEL" ] && Error "$BOOT does not exist! Please set the correct /boot partition in /etc/fstab."
		BOOT=$(readlink -f /dev/disk/by-label/$BOOT_LABEL)
		;;
	*)
		[ ! -b $BOOT ] && Error "$BOOT does not exist! Please set the correct /boot partition in /etc/fstab."
		BOOT=$(readlink -f $BOOT)
		;;
esac

# Find the disk with the boot partition, and get its partition number
if [ ${BOOT:5:4} == nvme ] || [ ${BOOT:5:6} == mmcblk ]; then
	BOOT_DISK=$(echo $BOOT | cut -d 'p' -f 1)
	BOOT_PARTNO=$(echo $BOOT | cut -d 'p' -f 2)
elif [ ${BOOT:5:2} == hd ] || [ ${BOOT:5:2} == sd ] || [ ${BOOT:5:2} == vd ]; then
	BOOT_DISK=$(echo $BOOT | sed 's/[0-9]//g')
	BOOT_PARTNO=$(echo $BOOT | sed 's/[^0-9]*//g')
else
	Error "$BOOT is on an unsupported media type! Please set /boot partition in /etc/fstab to a partition on a HDD or flash storage."
fi
[ "$BOOT_DISK" == "$BOOT_PARTNO" ] && Error "$BOOT is a disk, not a partition! Please set a /boot partition in /etc/fstab."

Upgrade() {
	mkdir -p /boot/EFI/grub
	cp /usr/share/shim-signed/shimx64.efi /boot/EFI/grub/
	cp /usr/share/shim-signed/mmx64.efi /boot/EFI/grub/
	cp /usr/share/shim-signed/shimia32.efi /boot/EFI/grub/
	cp /usr/share/shim-signed/mmia32.efi /boot/EFI/grub/
	## Create UEFI boot entry
	EFI_BITS="$(cat /sys/firmware/efi/fw_platform_size 2> /dev/null)"
	if [ ! -z "$EFI_BITS" ]; then
		[ "$EFI_BITS" == 32 ] && efibootmgr --unicode -c -d $BOOT_DISK -p $BOOT_PARTNO -L "Shim" -l '\EFI\grub\shimia32.efi'
		[ "$EFI_BITS" == 64 ] && efibootmgr --unicode -c -d $BOOT_DISK -p $BOOT_PARTNO -L "Shim" -l '\EFI\grub\shimx64.efi'
	fi
}

case "$1" in
	install)
		echo "Installing Shim secure boot preloader..."
		Upgrade && echo "Installed Shim secure boot preloader successfully." || \
		echo "Installed Shim secure boot preloader with errors.";;
	upgrade)
		if [ -f /boot/EFI/grub/shimx64.efi ] || [ -f /boot/EFI/grub/shimia32.efi ]; then
			echo "Upgrading Shim secure boot preloader..."
			Upgrade && echo "Upgraded Shim secure boot preloader successfully." || \
			echo "Upgraded Shim secure boot preloader with errors."
		fi;;
	uninstall)
		echo "Not yet implemented";;
	*) Error "Unrecognised command \"$1\"";;
esac
