#!/bin/bash
[ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. $SCRIPT_DIR/../gpuinfo # Get GPU info
## This script will automatically configure up to 2 GPUs, 1 screen and 1 serverlayout.
## The secondary GPU config will always have "-secondary" appended to its filename,
## in order to avoid conflicts when 2 GPUs of the same type are installed
## (example: AMD Vega integrated graphics and AMD Radeon discrete graphics card).
## It does not look at what drivers are installed, it only looks at what GPUs are
## currently connected to the motherboard. Therefore, having the drivers installed for
## a GPU you don't have won't do anything bad. However, having a GPU installed but not
## installing its drivers may prevent Xorg from working properly/at all.

## Remove unused configs
[ $GPU0 != "amd" ] && rm /etc/X11/xorg.conf.d/20-amdgpu.conf &> /dev/null
[ $GPU0 != "intel" ] && rm /etc/X11/xorg.conf.d/20-intel.conf &> /dev/null
[ $GPU0 != "nvidia" ] && rm /etc/X11/xorg.conf.d/20-nvidia.conf &> /dev/null
if [ ! -z $GPU1 ]; then
	[ $GPU1 != "amd" ] && rm /etc/X11/xorg.conf.d/20-amdgpu-secondary.conf &> /dev/null
	[ $GPU1 != "intel" ] && rm /etc/X11/xorg.conf.d/20-intel-secondary.conf &> /dev/null
	[ $GPU1 != "nvidia" ] && rm /etc/X11/xorg.conf.d/20-nvidia-secondary.conf &> /dev/null
fi

## Configure primary and secondary GPUs (do not overwrite existing configs except new BusID)
## qemu-std reqires no configuration
if [ $GPU0 == "amd" ]; then
	cp -n /opt/vapour-os/vapour-os-gui/20-amdgpu.conf /etc/X11/xorg.conf.d/20-amdgpu.conf
	PIDENT="AMD Graphics"
	$SCRIPT_DIR/gpuconfig 20-amdgpu.conf $GPU0_BUSID "$PIDENT"
elif [ $GPU0 == "intel" ]; then
	cp -n /opt/vapour-os/vapour-os-gui/20-intel.conf /etc/X11/xorg.conf.d/20-intel.conf
	PIDENT="Intel Graphics"
	$SCRIPT_DIR/gpuconfig 20-intel.conf $GPU0_BUSID "$PIDENT"
elif [ $GPU0 == "nvidia" ]; then
	cp -n /opt/vapour-os/vapour-os-gui/20-nvidia.conf /etc/X11/xorg.conf.d/20-nvidia.conf
	PIDENT="Nvidia Graphics" && $SCRIPT_DIR/gpuconfig 20-nvidia.conf $GPU0_BUSID "$PIDENT"
fi
if [ ! -z $GPU1 ]; then
	if [ $GPU1 == "amd" ]; then
		cp -n /opt/vapour-os/vapour-os-gui/20-amdgpu.conf /etc/X11/xorg.conf.d/20-amdgpu-secondary.conf
		SIDENT="AMD Dedicated Graphics"
		$SCRIPT_DIR/gpuconfig 20-amdgpu-secondary.conf $GPU1_BUSID "$SIDENT"
	elif [ $GPU1 == "intel" ]; then
		cp -n /opt/vapour-os/vapour-os-gui/20-intel.conf /etc/X11/xorg.conf.d/20-intel-secondary.conf
		SIDENT="Intel Dedicated Graphics"
		$SCRIPT_DIR/gpuconfig 20-intel-secondary.conf $GPU1_BUSID "$SIDENT"
	elif [ $GPU1 == "nvidia" ]; then
		cp -n /opt/vapour-os/vapour-os-gui/20-nvidia.conf /etc/X11/xorg.conf.d/20-nvidia-secondary.conf
		SIDENT="Nvidia Dedicated Graphics"
		$SCRIPT_DIR/gpuconfig 20-nvidia-secondary.conf $GPU1_BUSID "$SIDENT"
	fi
fi

## Set Screen
echo "Section \"Screen\"" > /etc/X11/xorg.conf.d/30-screen.conf
echo "	Identifier \"$PIDENT\"" >> /etc/X11/xorg.conf.d/30-screen.conf
echo "	Device \"$PIDENT\"" >> /etc/X11/xorg.conf.d/30-screen.conf
echo "EndSection" >> /etc/X11/xorg.conf.d/30-screen.conf

## Set ServerLayout
echo "Section \"ServerLayout\"" > /etc/X11/xorg.conf.d/90-serverlayout.conf
echo "	Identifier \"layout\"" >> /etc/X11/xorg.conf.d/90-serverlayout.conf
echo "	Screen 0 \"$PIDENT\"" >> /etc/X11/xorg.conf.d/90-serverlayout.conf
[ ! -z $GPU1 ] && [ $GPU1 == "nvidia" ] && echo "	Option \"AllowNVIDIAGPUScreens\"" >> /etc/X11/xorg.conf.d/90-serverlayout.conf
echo "EndSection" >> /etc/X11/xorg.conf.d/90-serverlayout.conf
