Section "InputClass"
    Identifier "system-keyboard"
    MatchIsKeyboard "on"
    Option "XkbLayout" "gb"
EndSection

Section "Device"
    Identifier "Intel Graphics"
    Driver "intel"
    Option "VideoRam" "262144"
    Option "TearFree" "false"
    Option "SwapbuffersWait" "false"
    Option "TripleBuffer" "false"
EndSection

Section "Device"
    Identifier "Nvidia Card"
    Driver "nvidia"
    VendorName "NVIDIA Corporation"
    BoardName "GeForce GTX 1660 Ti Mobile"
    Option "RegistryDwords" "PowerMizerEnable=0x1; PowerMizerDefaultAC=0x3; PowerMizerLevelAC=0x3; PowerMizerLevel=0x3; PerfLevelSrc=0x2222;"
    Option "TripleBuffer" "false"
    Option "NoFlip" "true"
    Option "UBB" "false"
EndSection
