#!/bin/bash
# Copy config files but preserve target permissions.
# Copy configs in specified directory. Then find any subdirectories and repeat for each one.
SCRIPT_DIR=/opt/vapour-os
SOURCE_DIR="$1"
TARGET_DIR="$2"
# Error handling
if [ -z "$SOURCE_DIR" ]; then
	echo "[ERROR] You must specify a source and target directory!"; exit 1
elif [ ! -d "$SOURCE_DIR" ]; then
	echo "[ERROR] Source directory \"$SOURCE_DIR\" does not exist!"
elif [ -z "$TARGET_DIR" ]; then
	echo "[ERROR] You must specify a target directory!"; exit 1
fi
mkdir -p "$TARGET_DIR"
IFS=$'\n'
for ENTRY in $(ls -A "$SOURCE_DIR"); do
	SOURCE_PATH="$SOURCE_DIR/$ENTRY"
	TARGET_PATH="$TARGET_DIR/$ENTRY"
	[ -f "$SOURCE_PATH" ] && cat "$SOURCE_PATH" > "$TARGET_PATH"
	[ -d "$SOURCE_PATH" ] && "$0" "$SOURCE_PATH" "$TARGET_PATH"
done
