[defaults]
### NTFS specific filesystem type options
ntfs_defaults=uid=$UID,gid=$GID,dmask=022,fmask=133,noatime,prealloc,sys_immutable,showmeta,show_sys_files=1
# ntfs_allow=uid=$UID,gid=$GID,umask,dmask,fmask,locale,norecover,ignore_case,windows_names,compression,nocompression,big_writes
