#!/bin/sh
[ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

[ -z "$($SCRIPT_DIR/../setvar query /etc/environment WINEESYNC)" ] && $SCRIPT_DIR/../setvar set /etc/environment WINEESYNC 1
[ -z "$($SCRIPT_DIR/../setvar query /etc/environment DXVK_CONFIG_FILE)" ] && $SCRIPT_DIR/../setvar set /etc/environment DXVK_CONFIG_FILE /etc/dxvk.conf
[ -z "$($SCRIPT_DIR/../setvar query /etc/environment DXVK_LOG_PATH)" ] && $SCRIPT_DIR/../setvar set /etc/environment DXVK_LOG_PATH none
[ -z "$($SCRIPT_DIR/../setvar query /etc/environment DXVK_LOG_LEVEL)" ] && $SCRIPT_DIR/../setvar set /etc/environment DXVK_LOG_LEVEL none
[ -z "$($SCRIPT_DIR/../setvar query /etc/environment VKD3D_CONFIG)" ] && $SCRIPT_DIR/../setvar set /etc/environment VKD3D_CONFIG force_host_cached,force_static_cbv
[ -z "$($SCRIPT_DIR/../setvar query /etc/environment VKD3D_DEBUG)" ] && $SCRIPT_DIR/../setvar set /etc/environment VKD3D_DEBUG none
[ -z "$($SCRIPT_DIR/../setvar query /etc/environment VKD3D_SHADER_DEBUG)" ] && $SCRIPT_DIR/../setvar set /etc/environment VKD3D_SHADER_DEBUG none
[ -z "$($SCRIPT_DIR/../setvar query /etc/environment VKD3D_TEST_DEBUG)" ] && $SCRIPT_DIR/../setvar set /etc/environment VKD3D_TEST_DEBUG 0
