Section "Device"
	Identifier "Nvidia Dedicated Graphics"
	Driver "nvidia"
	VendorName "NVIDIA Corporation"
	Option "GLShaderDiskCache" "true"
	Option "TripleBuffer" "false"
	Option "EnableACPIBrightnessHotkeys" "false"
	# You should set this to: 1000*(1/<monitor refresh rate>) (round down to lowest integer)
	# For example, 4ms is a good value for a 240Hz monitor: 1000*(1/240) = 4.16666666667 (round down to 4)
	Option "EmulatedOverlaysTimerMs" "4"
	# I have not yet tested the following options. These may have a positive or negative impact on performance,
	# solve problems or cause additional problems. USE AT YOUR OWN RISK.
	#Option "EmulatedOverlaysThresholdValue" "5"
	#Option "MultisampleCompatibility" "true"
	#Option "Interactive" "false"
	#Option "UseSysmemPixmapAccel" "false"
	#Option "ConnectToAcpid" "false"
	BusID "PCI:1:0:0"
EndSection
