# This file is included with the Vapour OS Nvidia package.
# You may edit this file, and all changes will be kept after an update.
Section "Device"
	Identifier "Nvidia Card"
	Driver "nvidia"
	Option "TripleBuffer" "false"
	Option "NoFlip" "true"
	Option "UBB" "false"
	Option "NoLogo" "true"
EndSection
