#!/bin/bash
[ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
VERBOSE=1
ATTEMPTS=5
Log() {
	echo "$(date +[%Y-%m-%dT%H:%M:%S%z]) [VAPOUR-OS-AUTOUPDATE] $1" >> /var/log/pacman.log
	[ ! -z $VERBOSE -a $VERBOSE == 1 ] && echo "$1"
}

## Update databases then download packages, but do not install them.
## It will attempt to download updates up to 5 times if it fails
Log "Starting automatic update..."
[ -z $ATTEMPTS ] || (($ATTEMPTS < 1)) ATTEMPTS=5
ATTEMPT=1; while (($ATTEMPT <= $ATTEMPTS)); do
	pacman --noconfirm -Syuqw && FAIL=0 || FAIL=1
	if [ $FAIL == 1 ]; then
		(($ATTEMPT < $ATTEMPTS)) && Log "Failed to download updates, retrying..."
		((ATTEMPT++))
	fi
done;
if [ $FAIL == 1 ]; then Log "[ERROR] Failed to download updates $ATTEMPTS times, exiting..."; exit 1
else Log "Updates downloaded successfully."
fi
