#!/usr/bin/env bash
DISTRO_ID="vapour-os"
kernel="$1"
[[ -n "$kernel" ]] || exit 0
/usr/lib/$DISTRO_ID/machine-owner-key

# use already installed kernel if it exists
[[ ! -f "$KERNELDESTINATION" ]] || kernel="$KERNELDESTINATION"

keypairs=(/etc/$DISTRO_ID/mok/MOK.key /etc/$DISTRO_ID/mok/MOK.crt)

for (( i=0; i<${#keypairs[@]}; i+=2 )); do
    key="${keypairs[$i]}" cert="${keypairs[(( i + 1 ))]}"
    if ! sbverify --cert "$cert" "$kernel" &>/dev/null; then
        sbsign --key "$key" --cert "$cert" --output "$kernel" "$kernel"
    fi
done
