#!/bin/sh
DISTRO_ID="vapour-os"
. /usr/lib/$DISTRO_ID/diskinfo &> /dev/null # Check if media partition exists

SetDir() { # $1: Folder name, $2: Folder location
	export XDG_$1_DIR="$2"
	if [ "$(/usr/lib/$DISTRO_ID/setvar query "/home/$USER/.config/user-dirs.dirs" "XDG_$1_DIR")" != "$2" ]; then
		mkdir -p "$XDG_$1_DIR" &> /dev/null
		xdg-user-dirs-update --set $1 "$2"
	fi
}

## Guest setup
if [ "$USER" == "guest" ]; then
	mkdir /tmp/guest; chmod 700 /tmp/guest # Create guest home directory
	for FILE in $(ls -A /etc/skel); do # Copy files from /etc/skel
		cp -nr --no-preserve=all /etc/skel/$FILE /tmp/guest;
	done
fi

# Create and set XDG home dirs in /media/$USER (if available and not root/guest) or /home/$USER
if [ "$USER" != "root" -a "$USER" != "guest" ]; then
	SetDir DESKTOP "/home/$USER/Desktop"
	if [ ! -z $MEDIA_DEV ]; then
		(mkdir /media/$USER; chmod 700 /media/$USER) &> /dev/null
		SetDir DOWNLOAD "/media/$USER/Downloads"
		SetDir TEMPLATES "/media/$USER/Templates"
		SetDir PUBLICSHARE "/media/$USER/Public"
		SetDir DOCUMENTS "/media/$USER/Documents"
		SetDir MUSIC "/media/$USER/Music"
		SetDir PICTURES "/media/$USER/Pictures"
		SetDir VIDEOS "/media/$USER/Videos"
	else
		SetDir DOWNLOAD "/home/$USER/Downloads"
		SetDir TEMPLATES "/home/$USER/Templates"
		SetDir PUBLICSHARE "/home/$USER/Public"
		SetDir DOCUMENTS "/home/$USER/Documents"
		SetDir MUSIC "/home/$USER/Music"
		SetDir PICTURES "/home/$USER/Pictures"
		SetDir VIDEOS "/home/$USER/Videos"
	fi
fi

export PATH="${PATH}:/home/$USER/.local/bin"

# Load user settings if they exist. If not, create them and load default settings.
mkdir -p "$HOME/.config/$DISTRO_ID" &> /dev/null
if [ ! -f "$HOME/.config/$DISTRO_ID/display.conf" ]; then
	echo "# Do not edit this file, use syscfg instead."
	echo ""
fi
. "$HOME/.config/$DISTRO_ID/display.conf"
