#!/bin/sh
SCALING_DRIVER=$(cat /sys/devices/system/cpu/cpufreq/policy0/scaling_driver)
AVAILABLE_GOVERNORS=$(cat /sys/devices/system/cpu/cpufreq/policy0/scaling_available_governors)

# Set CPUFreq governor
if [ $SCALING_DRIVER == "intel_pstate" ]; then
	if [[ " $AVAILABLE_GOVERNORS " == *" powersave "* ]]; then
		SCALING_GOVERNOR="powersave"
	fi
else
	if [[ " $AVAILABLE_GOVERNORS " == *" schedutil "* ]]; then SCALING_GOVERNOR="schedutil"
	elif [[ " $AVAILABLE_GOVERNORS " == *" conservative "* ]]; then SCALING_GOVERNOR="conservative"
	elif [[ " $AVAILABLE_GOVERNORS " == *" ondemand "* ]]; then SCALING_GOVERNOR="ondemand"; fi
fi
for CPU in $(ls -d /sys/devices/system/cpu/cpufreq/policy*); do
	echo "$SCALING_GOVERNOR" > $CPU/scaling_governor
done

# Set CPUIdle governor
echo "teo" > /sys/devices/system/cpu/cpuidle/current_governor
