#!/bin/sh 
#[ $(whoami) != "root" ] && echo "[ERROR] You must run this script with root priviliges." && exit 1
unset DEVICE_IWLWIFI

## Detect devices
PCI_DEVICES=$(lspci -mm)
IFS=$'\n' # Set delimiter to newline instead of space
for ENTRY in $PCI_DEVICES; do
	eval "ENTRY=($ENTRY)"
	SLOT="${ENTRY[0]}"
	CLASS="${ENTRY[1]}"
	VENDOR="${ENTRY[2]}"
	DEVICE="${ENTRY[3]}"
	
	if [ $CLASS == "VGA compatible controller" ]; then
		if [ $VENDOR == "Intel Corporation" ]; then
		elif [ $VENDOR == "NVIDIA Corporation" ]; then
		fi
	elif [ $CLASS == "Network controller" ]; then
		if [ $VENDOR == "Intel Corporation" ]; then
			DEVICE_IWLWIFI=1
		fi
	elif [ $CLASS == "Audio device" ]; then
		if [ $VENDOR == "Intel Corporation" ]; then
		fi
	fi
done

## Configure devices

## Clean up unused config files
