# This file is included with the Vapour OS legacy Intel Graphics package.
# You may edit this file, and all changes will be kept after an update.
Section "Device"
	Identifier "Intel Graphics"
	Driver "intel"
	Option "TearFree" "false"
	Option "SwapbuffersWait" "false"
	Option "TripleBuffer" "false"
EndSection
